export const CHANGE_INPUT = 'changeInput'
export const ADD_ITEM = 'addItem'
export const DELETE_ITEM = 'deleteItem'
export const GET_MY_LIST = 'getMyList'
// export const GET_DATA = 'getData'
// export const SET_DATA = 'setData'